/*:
 * @target MZ
 * @plugindesc クレセリウム：デプロイ時の独自素材保持用
 * @author Yoizuki Akari Company / OpenAI
 *
 * @help
 * 「未使用ファイルを除外する」を有効にしてデプロイする際、
 * 下記の素材を削除対象から外すためのプラグインです。
 *
 * old フォルダ配下の素材は意図的に保持対象から除外しています。
 * ゲーム中の処理は行いません。
 *
 * @requiredAssets img/characters/add/$abyss_demon
 * @requiredAssets img/characters/add/$abyss_demon_bk
 * @requiredAssets img/characters/add/$abyss_demon_bk2
 * @requiredAssets img/characters/add/crey/669456540
 * @requiredAssets img/characters/add/crey/d
 * @requiredAssets img/characters/add/crey/w
 * @requiredAssets img/characters/add/rabby
 * @requiredAssets img/characters/add/scratch_tallies
 * @requiredAssets img/characters/add/scratch_tallies_bk
 * @requiredAssets img/characters/add/sera/391679830
 * @requiredAssets img/characters/add/sera/d
 * @requiredAssets img/characters/add/sera/w
 * @requiredAssets img/enemies/add/0f/alchemist
 * @requiredAssets img/enemies/add/0f/hunter
 * @requiredAssets img/enemies/add/0f/knight
 * @requiredAssets img/enemies/add/0f/light_orb_v2
 * @requiredAssets img/enemies/add/0f/lord
 * @requiredAssets img/enemies/add/0f/mage
 * @requiredAssets img/enemies/add/0f/priestess
 * @requiredAssets img/enemies/add/1f/flutter_sd_battler_v2
 * @requiredAssets img/enemies/add/1f/goblin_sd_battler_v3
 * @requiredAssets img/enemies/add/1f/magium_battler_final
 * @requiredAssets img/enemies/add/1f/rabby_sd_battler
 * @requiredAssets img/enemies/add/1f/slime_sd_battler_v2
 * @requiredAssets img/enemies/add/2f/harpy_battler
 * @requiredAssets img/enemies/add/2f/hornet_battler
 * @requiredAssets img/enemies/add/2f/old2/harpy_battler
 * @requiredAssets img/enemies/add/2f/old2/warg_battler
 * @requiredAssets img/enemies/add/2f/small/hornet_battler
 * @requiredAssets img/enemies/add/2f/small/steed_battler
 * @requiredAssets img/enemies/add/2f/small/taron_battler
 * @requiredAssets img/enemies/add/2f/steed_battler
 * @requiredAssets img/enemies/add/2f/taron_battler
 * @requiredAssets img/enemies/add/2f/warg_battler
 * @requiredAssets img/enemies/add/3f/axolotl_battler
 * @requiredAssets img/enemies/add/3f/frost_battler
 * @requiredAssets img/enemies/add/3f/karukinos_battler
 * @requiredAssets img/enemies/add/3f/lana_battler
 * @requiredAssets img/enemies/add/3f/riviera_battler_l
 * @requiredAssets img/enemies/add/4f/gargoyle_battler
 * @requiredAssets img/enemies/add/4f/leo_battler
 * @requiredAssets img/enemies/add/4f/lizardman_battler
 * @requiredAssets img/enemies/add/4f/sneak_battler_smaller
 * @requiredAssets img/enemies/add/4f/warlock_battler
 * @requiredAssets img/enemies/add/5F/abyss_demon_battler
 * @requiredAssets img/enemies/add/5F/fiend
 * @requiredAssets img/enemies/add/5F/ghoul
 * @requiredAssets img/enemies/add/5F/plague
 * @requiredAssets img/enemies/add/5F/skeleton
 * @requiredAssets img/enemies/add/5F/wisp_padded38
 * @requiredAssets img/enemies/add/5F/wisp_padded38_
 * @requiredAssets img/parallaxes/add/difficulity1
 * @requiredAssets img/parallaxes/add/difficulity1_resize
 * @requiredAssets img/pictures/add/Crescerium_MobileHelp
 * @requiredAssets img/pictures/add/clay/0
 * @requiredAssets img/pictures/add/clay/00001-669456540
 * @requiredAssets img/pictures/add/clay/1
 * @requiredAssets img/pictures/add/clay/14
 * @requiredAssets img/pictures/add/clay/15
 * @requiredAssets img/pictures/add/clay/2
 * @requiredAssets img/pictures/add/clay/21
 * @requiredAssets img/pictures/add/clay/3
 * @requiredAssets img/pictures/add/clay/4
 * @requiredAssets img/pictures/add/clay/5
 * @requiredAssets img/pictures/add/clay/6
 * @requiredAssets img/pictures/add/clay/7
 * @requiredAssets img/pictures/add/clay/material_clay
 * @requiredAssets img/pictures/add/difficulity1
 * @requiredAssets img/pictures/add/double/1
 * @requiredAssets img/pictures/add/fin
 * @requiredAssets img/pictures/add/secret_file/secret_1_1
 * @requiredAssets img/pictures/add/secret_file/secret_1_2
 * @requiredAssets img/pictures/add/secret_file/secret_1_3
 * @requiredAssets img/pictures/add/secret_file/secret_2_1
 * @requiredAssets img/pictures/add/secret_file/secret_2_2
 * @requiredAssets img/pictures/add/secret_file/secret_2_3
 * @requiredAssets img/pictures/add/secret_file/secret_2_4
 * @requiredAssets img/pictures/add/secret_file/secret_2_5
 * @requiredAssets img/pictures/add/secret_file/secret_2_6
 * @requiredAssets img/pictures/add/secret_file/secret_2_7
 * @requiredAssets img/pictures/add/secret_file/secret_3_1
 * @requiredAssets img/pictures/add/secret_file/secret_3_2
 * @requiredAssets img/pictures/add/secret_file/secret_3_3
 * @requiredAssets img/pictures/add/secret_file/secret_3_4
 * @requiredAssets img/pictures/add/secret_file/secret_3_5
 * @requiredAssets img/pictures/add/secret_file/secret_3_6
 * @requiredAssets img/pictures/add/secret_file/secret_3_bk
 * @requiredAssets img/pictures/add/secret_file/secret_4_1
 * @requiredAssets img/pictures/add/secret_file/secret_4_2
 * @requiredAssets img/pictures/add/secret_file/secret_4_3
 * @requiredAssets img/pictures/add/secret_file/secret_4_4
 * @requiredAssets img/pictures/add/secret_file/secret_4_5
 * @requiredAssets img/pictures/add/secret_file/secret_4_6
 * @requiredAssets img/pictures/add/secret_file/secret_5_1
 * @requiredAssets img/pictures/add/secret_file/secret_5_2
 * @requiredAssets img/pictures/add/secret_file/secret_5_3
 * @requiredAssets img/pictures/add/secret_file/secret_5_4
 * @requiredAssets img/pictures/add/secret_file/secret_5_5
 * @requiredAssets img/pictures/add/secret_file/secret_5_6
 * @requiredAssets img/pictures/add/sera/0
 * @requiredAssets img/pictures/add/sera/1
 * @requiredAssets img/pictures/add/sera/10
 * @requiredAssets img/pictures/add/sera/11
 * @requiredAssets img/pictures/add/sera/12
 * @requiredAssets img/pictures/add/sera/13
 * @requiredAssets img/pictures/add/sera/14
 * @requiredAssets img/pictures/add/sera/16
 * @requiredAssets img/pictures/add/sera/2
 * @requiredAssets img/pictures/add/sera/21
 * @requiredAssets img/pictures/add/sera/3
 * @requiredAssets img/pictures/add/sera/4
 * @requiredAssets img/pictures/add/sera/5
 * @requiredAssets img/pictures/add/sera/6
 * @requiredAssets img/pictures/add/sera/7
 * @requiredAssets img/pictures/add/sera/8
 * @requiredAssets img/pictures/add/sera/9
 * @requiredAssets img/pictures/add/sera/material_sera
 * @requiredAssets img/pictures/add/戦闘システム設計
 * @requiredAssets img/titles1/add/logo/logo
 * @requiredAssets img/titles1/add/logo/logo_752
 * @requiredAssets img/titles1/add/logo/logo_760
 * @requiredAssets img/titles1/add/logo/logo_800
 * @requiredAssets img/titles1/add/logo/logo_v2
 * @requiredAssets img/titles1/add/logo/logo_v2_a
 * @requiredAssets img/titles1/add/title
 * @requiredAssets img/titles1/add/title_logo
 * @requiredAssets img/titles1/add/title_logo2
 * @requiredAssets img/titles1/add/title_logo3
 * @requiredAssets img/titles1/add/title_logo760
 * @requiredAssets img/titles1/add/title_v2
 * @requiredAssets img/titles1/add/title_v3
 */
(() => {
    "use strict";
})();
